logging.level.com.ratnikau.bankexpenselimits=INFO
logbook.format.style=http
app.pending-retry-delay=PT1H
rates.provider.api-key=test-key
rates.provider.backoff=10ms
rates.provider.connect-timeout=1s
rates.provider.read-timeout=1s
logging.level.org.zalando.logbook.Logbook=INFO